const questions = [
  {
    question: "What is the formula for velocity?",
    subject: "Physics",
    topic: "Motion",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Define Newton's first law of motion.",
    subject: "Physics",
    topic: "Laws of Motion",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the chemical symbol for water?",
    subject: "Chemistry",
    topic: "Chemical Elements",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Define pH.",
    subject: "Chemistry",
    topic: "Acids and Bases",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Solve: 2x + 5 = 15",
    subject: "Mathematics",
    topic: "Equations",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the capital of Australia?",
    subject: "Geography",
    topic: "Countries and Capitals",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Find the area of a rectangle with length 6 and width 4.",
    subject: "Mathematics",
    topic: "Geometry",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Who wrote 'Romeo and Juliet'?",
    subject: "Literature",
    topic: "Shakespearean Plays",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the main function of the mitochondria?",
    subject: "Biology",
    topic: "Cell Biology",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "Explain the concept of work in physics.",
    subject: "Physics",
    topic: "Work and Energy",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "What is the law of reflection?",
    subject: "Physics",
    topic: "Optics",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "Balancing chemical equations: H2 + O2 -> H2O",
    subject: "Chemistry",
    topic: "Chemical Reactions",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "What is the periodic table?",
    subject: "Chemistry",
    topic: "Chemical Elements",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "Solve: 3x - 7 = 14",
    subject: "Mathematics",
    topic: "Equations",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "Find the volume of a cylinder with radius 3 and height 10.",
    subject: "Mathematics",
    topic: "Geometry",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "Explain the theory of relativity.",
    subject: "Physics",
    topic: "Relativity",
    difficulty: "Hard",
    marks: 20,
  },
  {
    question: "Describe the properties of black holes.",
    subject: "Physics",
    topic: "Astrophysics",
    difficulty: "Hard",
    marks: 20,
  },
  {
    question: "Explain the concept of chemical equilibrium.",
    subject: "Chemistry",
    topic: "Chemical Equilibrium",
    difficulty: "Hard",
    marks: 20,
  },
  {
    question: "Discuss the principles of organic chemistry.",
    subject: "Chemistry",
    topic: "Organic Chemistry",
    difficulty: "Hard",
    marks: 20,
  },
  {
    question: "Solve the Navier-Stokes equations.",
    subject: "Mathematics",
    topic: "Fluid Dynamics",
    difficulty: "Hard",
    marks: 20,
  },
  {
    question: "Prove Fermat's Last Theorem.",
    subject: "Mathematics",
    topic: "Number Theory",
    difficulty: "Hard",
    marks: 20,
  },
];

module.exports = {
  getQuestions: () => questions,
};
